### ISSUE TITLE
help , error compilation terminated.

### ISSUE THREAD

**Issue by ghost** [atcsecure/XC_XBridge#6]
root@u19757984:~/XC_XBridge# cd/src make -f makefile.unix USE_UPNP= BDB_INCLUDE_PATH='/usr/include/db4.8'
-bash: cd/src: No such file or directory
root@u19757984:~/XC_XBridge# cd src 
root@u19757984:~/XC_XBridge/src# make -f makefile.unix USE_UPNP= BDB_INCLUDE_PATH='/usr/include/db4.8'
g++ -c -O2 -msse2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/root/XC_XBridge/src -I/root/XC_XBridge/src/obj -I/usr/include/db4.8 -DUSE_IPV6=1 -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/alert.d -o obj/alert.o alert.cpp
alert.cpp:244:1: fatal error: opening dependency file obj/alert.d: No such file or directory
 }
 ^
compilation terminated.
make: *** [obj/alert.o] Error 1

**Comment by atcsecure** [comment]
I have pushed a fix to the repo and merged to master.  You should be all set ( the error is because obj directory does not exist )
